Update rundaily.yml

diff --git a/.github/workflows/rundaily.yml b/.github/workflows/rundaily.yml
--- a/.github/workflows/rundaily.yml
+++ b/.github/workflows/rundaily.yml
@@ -15,14 +15,15 @@ jobs:
 
       - name: Use the Secret
         env:
-            GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
+          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
         run: |
-            echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json
-            if [ -s "credentials.json" ]; then
-                  gcloud auth activate-service-account --key-file=credentials.json
-            else
-              echo "Error: credentials.json is empty or not found."
-              exit 1
+          echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json
+          if [ -s "credentials.json" ]; then
+              gcloud auth activate-service-account --key-file=credentials.json
+          else
+            echo "Error: credentials.json is empty or not found."
+            exit 1
+          fi
 
       - name: Set up Python
         uses: actions/setup-python@v2
